/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#ifndef H_OS_LINK_TABLES_
#define H_OS_LINK_TABLES_

/**
 * @brief Helper macros for accessing link time tables
 *
 * Link time tables are compile time constant tables that are
 * constructed during linking aggregating symbols for specific
 * linker section.
 * Object put in the section should be of the same size to be
 * treated as array elements.
 *
 * To create named section that can be used as link time table
 * without manual modification of linker script newt tool
 * recognizes following section in pkg.yml
 *
 * pkg.link_tables:
 *     - example_table1
 *     - example_table2
 *
 * This creates entries in autogenerated linker script include file
 * link_table.ld.h, those entries gather symbol of sections names:
 *  .example_table1
 *  .example_table1.*
 * and
 *  .example_table2
 *  .example_table2.*
 *
 * To put element in those section user code can specify section
 * name in variable definition.
 *
 * Following macro creates external table that can be access just
 * as it would be defined explicitly.
 *
 * LINK_TABLE(struct foo, example1_table)
 * LINK_TABLE(uint32_t, example2_table)
 *
 * Declares tables that are equivalent to:
 *
 * const struct foo example1_table[size1];
 * const uint32_t example2_table[size2];
 *
 * Size of table is unknown at compile time but can be determined
 * in runtime, depending on how many elements are actually put
 * in those arrays.
 *
 * To put element in such array user code has to specify matching
 * section name:
 *
 * const struct foo foo1 __attribute__((section(".example1_table"))) = {};
 * const uint32_t val1 __attribute__((section(".example2_table"))) = {};
 * const uint32_t val2 __attribute__((section(".example2_table"))) = {};
 */

#define LINK_TABLE_START(table_name) __ ## table_name ## _start__
#define LINK_TABLE_END(table_name) __ ## table_name ## _end__
#define LINK_TABLE_SIZE(table_name) table_name ## _size()
#define LINK_TABLE_ELEMENT_TYPE(table_name) table_name ## _element_t
#define LINK_TABLE_SECTION(table_name) __attribute__((section("."#table_name)))
#define LINK_TABLE_ELEMENT_SECTION(table_name, elem) __attribute__((section("."#table_name "."#elem)))

#define LINK_TABLE(element_type, table_name)                              \
    typedef const element_type table_name ## _element_t;                  \
    extern element_type const table_name[];                               \
    extern element_type const LINK_TABLE_START(table_name)[];             \
    extern element_type const LINK_TABLE_END(table_name)[];               \
    static inline size_t table_name ## _size(void) {                      \
        return LINK_TABLE_END(table_name) - LINK_TABLE_START(table_name); \
    }

/**
 * Simple inline loop for link table tables
 *
 * @param table - name of table as defined in pkg.link_tables: section
 * @param type - type of element in table
 * @param fun - function to call for each element of the table.
 *              Function should have prototype like this: void fun(type *element)
 */
#define LINK_TABLE_FOR_EACH(table, fun)                 \
    {                                                   \
        table_ ## _element_t *entry;                    \
        for (entry = table;                             \
             entry != LINK_TABLE_END(table); ++entry) { \
            fun(entry);                                 \
        }                                               \
    }

#define FOR_LINK_TABLE(e, table)             \
    for (table ## _element_t *e = (table ## _element_t *)LINK_TABLE_START(table); e != LINK_TABLE_END(table); ++e)

#define LINK_TABLE_ELEMENT_INDEX(table, e) ((e) - (table))

#endif
