syscfg.vals:
    CRYPTO: 1
    MBEDTLS_AES_ALT: 1
    MBEDTLS_ECDH_COMPUTE_SHARED_ALT: 1
    MBEDTLS_ECDSA_SIGN_ALT: 1
    MBEDTLS_ECDSA_VERIFY_ALT: 1
    MBEDTLS_ECDSA_GENKEY_ALT: 1
    MBEDTLS_ENTROPY_HARDWARE_ALT: 1
